{
  system,
  nixpkgs,
}:

# Hermetic, pure build of the Compose/Wasm browser bundle. A single mitm-cache fixed-output
# derivation captures all build network traffic — Maven (Gradle) deps AND the npm registry
# (@sqlite.org/sqlite-wasm + the Kotlin webpack toolchain) — under one hash in ./web-deps.json.
#
# Crucially we set `gradleUpdateTask` to the *real* build task instead of nixpkgs' default
# `nixDownloadDeps`: the latter blindly resolves every configuration, which fails on AGP/KMP
# (ambiguous Android variants like androidHostTestCompileClasspath). Running the actual wasm task
# resolves only what it needs, in proper task-graph context, and the proxy records exactly those
# deps. Regenerate the lock with `nix run .#update-web-deps` (no hand-edited hash).
let
  pkgs = import nixpkgs {
    inherit system;
    config.allowUnfree = true;
    config.android_sdk.accept_license = true;
  };

  jdk = pkgs.jdk21;

  # :composeApp is a combined Android + web module, so Gradle configures the Android plugin even for
  # the wasmJs task and needs the SDK present (it isn't in the web output). Mirror shell.nix.
  buildToolsVersion = "37.0.0";
  androidSdk = pkgs.androidenv.composeAndroidPackages {
    buildToolsVersions = [ buildToolsVersion ];
    platformVersions = [ "37" ];
    includeNDK = false;
    includeEmulator = false;
  };
  sdkRoot = "${androidSdk.androidsdk}/libexec/android-sdk";

  # Must match KOTLIN_NODE_VERSION / nodeDir in build.gradle.kts and shell.nix.
  nodeVersion = "25.0.0";
  nodeDir = "node-v${nodeVersion}-linux-${if system == "aarch64-linux" then "arm64" else "x64"}";

  fs = pkgs.lib.fileset;
  root = ../.;

  wasmTask = ":composeApp:wasmJsBrowserDistribution";
in
pkgs.stdenv.mkDerivation (finalAttrs: {
  pname = "quits-web";
  version = "0.1.0";

  src = fs.toSource {
    inherit root;
    fileset = fs.unions [
      (root + "/composeApp")
      (root + "/sqliteWebWorker")
      (root + "/androidApp")
      (root + "/gradle")
      (root + "/build.gradle.kts")
      (root + "/settings.gradle.kts")
      (root + "/gradle.properties")
      (root + "/gradlew")
      (root + "/kotlin-js-store")
    ];
  };

  nativeBuildInputs = [
    # AGP 9.2.1 needs Gradle >= 9.4.1; pkgs.gradle is still 8.x. (The devshell uses ./gradlew 9.5.1.)
    pkgs.gradle_9
    jdk
    pkgs.nodejs
    pkgs.yarn
    androidSdk.androidsdk
  ];

  # Single FOD covering Maven + npm. The hash lives in ./web-deps.json (generated by updateScript).
  mitmCache = pkgs.gradle_9.fetchDeps {
    pkg = finalAttrs.finalPackage;
    data = ./web-deps.json;
  };
  __darwinAllowLocalNetworking = true;

  # Run the real wasm build for both dep capture (update) and the offline build, not nixDownloadDeps.
  gradleBuildTask = wasmTask;
  gradleUpdateTask = wasmTask;
  # The nixDownloadDeps/configurations closure breaks under Gradle 9's configuration cache anyway.
  gradleFlags = [ "--no-configuration-cache" ];

  env = {
    ANDROID_HOME = sdkRoot;
    JAVA_HOME = "${jdk}";
    KOTLIN_NODE_HOME = "${pkgs.nodejs}";
    KOTLIN_NODE_VERSION = nodeVersion;
    GRADLE_OPTS = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${sdkRoot}/build-tools/${buildToolsVersion}/aapt2";
  };

  # preBuild runs in both the build and the dep-capture update, after gradleConfigureHook has set
  # GRADLE_USER_HOME — so the SDK path and the Nix-node symlink are in place before Gradle starts.
  preBuild = ''
    cat > local.properties <<EOF
    sdk.dir=${sdkRoot}
    EOF
    mkdir -p "$GRADLE_USER_HOME/nodejs"
    ln -sfn ${pkgs.nodejs} "$GRADLE_USER_HOME/nodejs/${nodeDir}"
  '';

  doCheck = false;

  installPhase = ''
    runHook preInstall
    mkdir -p $out
    cp -r composeApp/build/dist/wasmJs/productionExecutable/. $out/
    runHook postInstall
  '';

  passthru.updateScript = finalAttrs.mitmCache.updateScript;

  meta = {
    description = "Quits web app (Kotlin/Wasm browser bundle)";
    license = pkgs.lib.licenses.agpl3Plus;
  };
})
