{
  system,
  nixpkgs,
}:

# Hermetic build of the Compose/Wasm browser bundle. Pure like nix/server.nix: a single mitm-cache
# fixed-output derivation captures *all* build network traffic — Maven (Gradle) deps and the npm
# registry (@sqlite.org/sqlite-wasm + the Kotlin webpack toolchain) — under one hash in
# ./web-deps.json. Regenerate it without hand-editing via `passthru.updateScript`
# (the `update-web-deps` workflow runs this and opens a PR).
let
  pkgs = import nixpkgs {
    inherit system;
    config.allowUnfree = true;
    config.android_sdk.accept_license = true;
  };

  jdk = pkgs.jdk21;

  # :composeApp is a combined Android + web module, so Gradle configures the Android plugin even for
  # the wasmJs task and needs the SDK present (it isn't in the web output). Mirror shell.nix.
  buildToolsVersion = "37.0.0";
  androidSdk = pkgs.androidenv.composeAndroidPackages {
    buildToolsVersions = [ buildToolsVersion ];
    platformVersions = [ "37" ];
    includeNDK = false;
    includeEmulator = false;
  };
  sdkRoot = "${androidSdk.androidsdk}/libexec/android-sdk";

  # Must match KOTLIN_NODE_VERSION / nodeDir in build.gradle.kts and shell.nix.
  nodeVersion = "25.0.0";
  nodeDir = "node-v${nodeVersion}-linux-${if system == "aarch64-linux" then "arm64" else "x64"}";

  fs = pkgs.lib.fileset;
  root = ../.;
in
pkgs.stdenv.mkDerivation (finalAttrs: {
  pname = "quits-web";
  version = "0.1.0";

  src = fs.toSource {
    inherit root;
    fileset = fs.unions [
      (root + "/composeApp")
      (root + "/sqliteWebWorker")
      (root + "/androidApp")
      (root + "/gradle")
      (root + "/build.gradle.kts")
      (root + "/settings.gradle.kts")
      (root + "/gradle.properties")
      (root + "/gradlew")
      (root + "/kotlin-js-store")
    ];
  };

  nativeBuildInputs = [
    pkgs.gradle
    jdk
    pkgs.nodejs
    pkgs.yarn
    androidSdk.androidsdk
  ];

  # Single FOD covering Maven + npm. The hash lives in ./web-deps.json (generated by updateScript).
  mitmCache = pkgs.gradle.fetchDeps {
    pkg = finalAttrs.finalPackage;
    data = ./web-deps.json;
  };
  __darwinAllowLocalNetworking = true;

  env = {
    ANDROID_HOME = sdkRoot;
    JAVA_HOME = "${jdk}";
    KOTLIN_NODE_HOME = "${pkgs.nodejs}";
    KOTLIN_NODE_VERSION = nodeVersion;
    GRADLE_OPTS = "-Dorg.gradle.project.android.aapt2FromMavenOverride=${sdkRoot}/build-tools/${buildToolsVersion}/aapt2";
  };

  preBuild = ''
    cat > local.properties <<EOF
    sdk.dir=${sdkRoot}
    EOF
    # NixOS can't run the node Kotlin would download; point its expected dir at the Nix node.
    mkdir -p "$GRADLE_USER_HOME/nodejs"
    ln -sfn ${pkgs.nodejs} "$GRADLE_USER_HOME/nodejs/${nodeDir}"
  '';

  gradleBuildTask = ":composeApp:wasmJsBrowserDistribution";
  doCheck = false;

  installPhase = ''
    runHook preInstall
    mkdir -p $out
    cp -r composeApp/build/dist/wasmJs/productionExecutable/. $out/
    runHook postInstall
  '';

  passthru.updateScript = finalAttrs.mitmCache.updateScript;

  meta = {
    description = "Quits web app (Kotlin/Wasm browser bundle)";
    license = pkgs.lib.licenses.agpl3Plus;
  };
})
